### ISSUE TITLE
[bitnami/elasticsearch] error calling gt: incompatible types for comparison

### ISSUE THREAD

**Issue by sida-khalibre** [bitnami/charts#5390]
**Which chart**:
The name (and version) of the affected chart
elasticsearch v14.2.0

**Describe the bug**
When set `metrics. enabled: true` produce error with message:
Error: UPGRADE FAILED: template: elasticsearch/templates/metrics-deploy.yaml:37:19: executing "elasticsearch/templates/metrics-deploy.yaml" at <gt .Values.coordinating.replicas 0>: error calling gt: incompatible types for comparison

**To Reproduce**

1. In values.yaml set 
    ```
    metrics:
      enabled: true
    ```
2. Run helm install

**Expected behavior**
Helm should run install successfully. 

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on 192.168.241.3:53: no such host
```

**Additional context**

**Comment by sida-khalibre** [comment]
Possible caused by PR https://github.com/bitnami/charts/pull/5364

**Comment by rafariossaa** [comment]
Hi,
  Could you check if this change fixes the issue for you ?

**Comment by sida-khalibre** [comment]
> Hi,
> Could you check if this change fixes the issue for you ?

That fix in 14.2.1
Thanks @rafariossaa
